POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXIiLCJpZCI6IjY3MzQ5MGI3Zjk1MTRjYTMyYTQ1NjE4YiIsImlhdCI6MTczMTUwMDg5NSwiZXhwIjoxNzMxNTA0NDk1fQ.PSjjcX4OHRU5ayzfsI4Fo4yK3MwycR6MBxJkKWYyLak

{
    "title": "My first blog",
    "author": "Dave",
    "url": "/blogs/0/1",
    "likes": 1
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "My second blog",
    "author": "Dave",
    "url": "/blogs/0/2",
    "likes": 0
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Dave",
    "url": "/blogs/0/2",
    "likes": 0
}